FROM node:lts-hydrogen AS builder

WORKDIR /app
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY prisma ./prisma/
RUN npm install
COPY . ./
RUN npm build

FROM node:lts-hydrogen

ENV PORT=3000
ENV NODE_ENV=development
WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/prisma /app/prisma


EXPOSE 3000
CMD [ "yarn" ,"start:dev" ]
