version: '3.4'

services:
  app:
    container_name: app
    image: adryan29/suflex-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://suflex:suflex@db:5432/suflex?schema=public
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
  db:
    container_name: db
    image: bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: suflex
      POSTGRESQL_PASSWORD: suflex
      POSTGRESQL_USERNAME: suflex
    healthcheck:
       test: [ "CMD", "pg_isready", "-q", "-d", "suflex", "-U", "suflex" ]
       interval : 5s
       timeout : 5s
       retries : 5
    ports:
      - 5432:5432
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
  certbot:
    container_name: certbot
    image: certbot/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email adryan.software@gmail.com -d suflex.adryan.me --agree-tos
    depends_on:
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot