version: '3.4'

services:
  app:
    container_name: app
    restart: always
    image: adryan29/suflex-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
  db:
    container_name: db
    restart: always
    image: bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: suflex
      POSTGRESQL_PASSWORD: suflex
      POSTGRESQL_USERNAME: suflex
    healthcheck:
       test: [ "CMD", "pg_isready", "-q", "-d", "suflex", "-U", "suflex" ]
       interval : 5s
       timeout : 5s
       retries : 5
    ports:
      - 5432:5432
  proxy:
    container_name: proxy
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - app